version: "3.9"

services:
  postgres:
    image: postgres:15.4
    volumes:
      - .volumes/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cicd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: always

  application:
    build: .
    container_name: app
    environment:
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/cicd
    depends_on:
      postgres:
        condition: service_started
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
