name: ci-cd
on: push

jobs:
  testing_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout репозитория
        uses: actions/checkout@v4

      - name: установка maven
        run: apt install maven -y

      - name: сборка проекта
        run: mvn clean verify

  docker_push_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout репозитория
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: сборка образа
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd-app:latest .

      - name: push docker images
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cicd-app:latest

  delpoy_job:
    runs-on: ubuntu-latest
    needs: docker_push_job
    steps:
      - name: deploy
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.SERVER_HOST }}
          SSH_USER: ${{ secrets.SERVER_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~
          if [ ! -d "app" ]; then
            git clone https://github.com/isshepelev/simple-CICD-app.git app
          else
            cd app
            git reset --hard  
            git pull origin main
          fi
          
          docker compose down || true

          docker pull ${{ secrets.DOCKER_USERNAME }}/cicd-app:latest

          docker compose up -d --build
