name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Maven
        run: sudo apt update && sudo apt install -y maven

      - name: Build and test
        run: mvn clean verify

  build_docker_job:
    runs-on: ubuntu-latest
    needs: test_job

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd-app:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cicd-app:latest

  deploy_job:
    runs-on: ubuntu-latest
    needs:
      - test_job
      - build_docker_job

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            apt update
            cd ~/app || mkdir ~/app && cd ~/app
            docker-compose pull
            docker-compose down
            docker-compose up -d --force-recreate --remove-orphans
